import type { Property, Guest, Booking } from './types'

function d(offset: number): string {
  const dt = new Date()
  dt.setDate(dt.getDate() + offset)
  return dt.toISOString().slice(0, 10)
}

function ts(offsetDays: number, hour = 10): string {
  const dt = new Date()
  dt.setDate(dt.getDate() + offsetDays)
  dt.setHours(hour, 0, 0, 0)
  return dt.toISOString()
}

export const mockProperties: Property[] = [
  {
    id: 'prop-1',
    nome: 'Apartamento Alfama',
    tipo: 'apartamento',
    endereco: 'Rua do Limoeiro, 12, 1100-001',
    cidade: 'Lisboa',
    capacidade: 4,
    quartos: 2,
    casasBanho: 1,
    comodidades: ['WiFi', 'AC', 'Cozinha', 'Máquina de lavar', 'Varanda', 'Vista cidade'],
    descricao: 'Apartamento com charme no coração de Alfama, com varanda e vista para a cidade. Ideal para casais ou famílias pequenas que querem descobrir Lisboa autêntica.',
    imagem_url: 'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?w=800&q=80',
    instrucoes_checkin: 'A chave está na caixa de segurança junto à porta principal. Código: 1234. Check-in a partir das 15h.',
    regras_casa: 'Não fumar. Silêncio a partir das 22h. Sem festas. Animais não permitidos.',
    preco_base: 95,
    cor: '#C2714F',
    ativo: true,
    criado_em: ts(-180),
  },
  {
    id: 'prop-2',
    nome: 'Studio Chiado',
    tipo: 'quarto',
    endereco: 'Rua Garrett, 45, 1200-205',
    cidade: 'Lisboa',
    capacidade: 2,
    quartos: 1,
    casasBanho: 1,
    comodidades: ['WiFi', 'AC', 'Cozinha compacta', 'Vista para o rio'],
    descricao: 'Studio moderno no Chiado, bairro mais fashionable de Lisboa. A dois passos de restaurantes, lojas e do elevador de Santa Justa.',
    imagem_url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
    instrucoes_checkin: 'Receção no rés-do-chão aberta das 9h às 21h. Após esse horário, contacte por mensagem.',
    regras_casa: 'Não fumar. Sem festas. Check-out até às 11h.',
    preco_base: 65,
    cor: '#4A7FA5',
    ativo: true,
    criado_em: ts(-150),
  },
  {
    id: 'prop-3',
    nome: 'T2 Cascais',
    tipo: 'moradia',
    endereco: 'Av. Dom Carlos I, 8, 2750-310',
    cidade: 'Cascais',
    capacidade: 5,
    quartos: 2,
    casasBanho: 2,
    comodidades: ['WiFi', 'AC', 'Cozinha', 'Jardim', 'Estacionamento', 'BBQ', 'Piscina'],
    descricao: 'Casa com jardim e piscina privada em Cascais, a 5 minutos da praia. Perfeita para famílias ou grupos. Estacionamento gratuito e BBQ disponível.',
    imagem_url: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
    instrucoes_checkin: 'Chave no cofre junto ao portão. Código enviado por SMS no dia do check-in.',
    regras_casa: 'Máximo 5 hóspedes. Sem festas. Animais permitidos com depósito adicional.',
    preco_base: 145,
    cor: '#5A8A6A',
    ativo: true,
    criado_em: ts(-120),
  },
]

export const mockGuests: Guest[] = [
  {
    id: 'guest-1',
    nome: 'Emma Schmidt',
    email: 'emma.schmidt@gmail.com',
    telefone: '+49 151 2345 6789',
    nacionalidade: 'Alemã',
    numero_documento: 'DE1234567',
    data_nascimento: '1988-03-15',
    tags: ['frequente', 'vip'],
    notas: 'Hóspede muito cuidadosa. Sempre deixa o apartamento impecável.',
    criado_em: ts(-300),
  },
  {
    id: 'guest-2',
    nome: 'James Wilson',
    email: 'j.wilson@outlook.com',
    telefone: '+44 7700 900123',
    nacionalidade: 'Britânica',
    tags: ['frequente'],
    criado_em: ts(-200),
  },
  {
    id: 'guest-3',
    nome: 'Marie Dubois',
    email: 'marie.dubois@laposte.fr',
    telefone: '+33 6 12 34 56 78',
    nacionalidade: 'Francesa',
    tags: ['novo'],
    criado_em: ts(-60),
  },
  {
    id: 'guest-4',
    nome: 'Sofia García',
    email: 'sofia.garcia@hotmail.es',
    telefone: '+34 612 345 678',
    nacionalidade: 'Espanhola',
    tags: ['vip'],
    notas: 'Sempre pede late check-out. Boa hóspede.',
    criado_em: ts(-90),
  },
  {
    id: 'guest-5',
    nome: 'Marco Rossi',
    email: 'marco.rossi@libero.it',
    telefone: '+39 333 1234567',
    nacionalidade: 'Italiana',
    tags: ['novo'],
    criado_em: ts(-30),
  },
  {
    id: 'guest-6',
    nome: 'Ana Ferreira',
    email: 'ana.ferreira@gmail.com',
    telefone: '+351 912 345 678',
    nacionalidade: 'Portuguesa',
    tags: ['problematico'],
    notas: 'Deixou danos na última estadia. Exigiu reembolso indevido. Cautela.',
    criado_em: ts(-45),
  },
]

export const mockBookings: Booking[] = [
  // Active check-ins (in house)
  {
    id: 'res-1',
    propriedade_id: 'prop-1',
    hospede_id: 'guest-1',
    check_in: d(-1),
    check_out: d(4),
    num_hospedes: 2,
    estado: 'checkin',
    origem: 'airbnb',
    preco_total: 475,
    preco_pago: 475,
    notas: 'Chegada ontem às 16h. Hóspede pediu toalhas extra.',
    criado_em: ts(-32),
    historico: [
      { id: 'ev-1', data: ts(-32), tipo: 'criada', descricao: 'Reserva criada via Airbnb' },
      { id: 'ev-2', data: ts(-32, 10), tipo: 'confirmada', descricao: 'Confirmada automaticamente' },
      { id: 'ev-3', data: ts(-1, 16), tipo: 'checkin', descricao: 'Check-in realizado' },
    ],
  },
  {
    id: 'res-2',
    propriedade_id: 'prop-2',
    hospede_id: 'guest-2',
    check_in: d(-2),
    check_out: d(1),
    num_hospedes: 1,
    estado: 'checkin',
    origem: 'booking',
    preco_total: 195,
    preco_pago: 195,
    criado_em: ts(-25),
    historico: [
      { id: 'ev-4', data: ts(-25), tipo: 'criada', descricao: 'Reserva criada via Booking.com' },
      { id: 'ev-5', data: ts(-25, 10), tipo: 'confirmada', descricao: 'Confirmada automaticamente' },
      { id: 'ev-6', data: ts(-2, 14), tipo: 'checkin', descricao: 'Check-in realizado' },
    ],
  },
  // Today checkout
  {
    id: 'res-3',
    propriedade_id: 'prop-3',
    hospede_id: 'guest-3',
    check_in: d(-3),
    check_out: d(0),
    num_hospedes: 3,
    estado: 'checkin',
    origem: 'direto',
    preco_total: 435,
    preco_pago: 435,
    criado_em: ts(-20),
    historico: [
      { id: 'ev-7', data: ts(-20), tipo: 'criada', descricao: 'Reserva direta por e-mail' },
      { id: 'ev-8', data: ts(-20, 14), tipo: 'confirmada', descricao: 'Confirmada manualmente' },
      { id: 'ev-9', data: ts(-3, 16), tipo: 'checkin', descricao: 'Check-in realizado' },
    ],
  },
  // Upcoming
  {
    id: 'res-4',
    propriedade_id: 'prop-1',
    hospede_id: 'guest-4',
    check_in: d(5),
    check_out: d(9),
    num_hospedes: 2,
    estado: 'confirmada',
    origem: 'airbnb',
    preco_total: 380,
    preco_pago: 0,
    criado_em: ts(-15),
    historico: [
      { id: 'ev-11', data: ts(-15), tipo: 'criada', descricao: 'Reserva criada via Airbnb' },
      { id: 'ev-12', data: ts(-15, 10), tipo: 'confirmada', descricao: 'Confirmada automaticamente' },
    ],
  },
  {
    id: 'res-5',
    propriedade_id: 'prop-2',
    hospede_id: 'guest-5',
    check_in: d(3),
    check_out: d(6),
    num_hospedes: 2,
    estado: 'confirmada',
    origem: 'booking',
    preco_total: 195,
    preco_pago: 97.50,
    notas: 'Hóspede pediu berço para bebé.',
    criado_em: ts(-12),
    historico: [
      { id: 'ev-13', data: ts(-12), tipo: 'criada', descricao: 'Reserva criada via Booking.com' },
      { id: 'ev-14', data: ts(-12, 10), tipo: 'confirmada', descricao: 'Confirmada automaticamente' },
      { id: 'ev-15', data: ts(-7, 9), tipo: 'pagamento', descricao: 'Pagamento parcial recebido: €97.50' },
    ],
  },
  {
    id: 'res-6',
    propriedade_id: 'prop-3',
    hospede_id: 'guest-1',
    check_in: d(14),
    check_out: d(21),
    num_hospedes: 4,
    estado: 'confirmada',
    origem: 'direto',
    preco_total: 1015,
    preco_pago: 507.50,
    criado_em: ts(-7),
    historico: [
      { id: 'ev-16', data: ts(-7), tipo: 'criada', descricao: 'Reserva direta — hóspede recorrente' },
      { id: 'ev-17', data: ts(-7, 10), tipo: 'confirmada', descricao: 'Confirmada manualmente' },
      { id: 'ev-18', data: ts(-7, 11), tipo: 'pagamento', descricao: 'Sinal de 50%: €507.50' },
    ],
  },
  // Pending
  {
    id: 'res-7',
    propriedade_id: 'prop-1',
    hospede_id: 'guest-6',
    check_in: d(11),
    check_out: d(13),
    num_hospedes: 3,
    estado: 'pendente',
    origem: 'outro',
    preco_total: 190,
    preco_pago: 0,
    notas: 'Confirmar identidade antes de aceitar.',
    criado_em: ts(-2),
    historico: [
      { id: 'ev-19', data: ts(-2), tipo: 'criada', descricao: 'Reserva criada manualmente' },
    ],
  },
  // Past booking
  {
    id: 'res-8',
    propriedade_id: 'prop-2',
    hospede_id: 'guest-4',
    check_in: d(-20),
    check_out: d(-16),
    num_hospedes: 2,
    estado: 'checkout',
    origem: 'airbnb',
    preco_total: 260,
    preco_pago: 260,
    criado_em: ts(-45),
    historico: [
      { id: 'ev-20', data: ts(-45), tipo: 'criada', descricao: 'Reserva criada via Airbnb' },
      { id: 'ev-21', data: ts(-45, 10), tipo: 'confirmada', descricao: 'Confirmada automaticamente' },
      { id: 'ev-22', data: ts(-20, 15), tipo: 'checkin', descricao: 'Check-in realizado' },
      { id: 'ev-23', data: ts(-16, 10), tipo: 'checkout', descricao: 'Check-out realizado' },
    ],
  },
]
